import type { AccountSessionStatus, BrowserProfileStatus, InputMedia, JobState, ProjectStatus, WorkerState } from '@ht-dola/shared';
import type { ProductionRun } from '@ht-dola/shared';

export interface ProjectRecord { id: string; name: string; description: string; status: ProjectStatus; outputDirectory: string | null; defaultProvider: string; defaultDurationSeconds: number; defaultAspectRatio: string; defaultResolution: string; createdAt: string; updatedAt: string; archivedAt: string | null; totalJobs: number; draftJobs: number; queuedJobs: number; runningJobs: number; completedJobs: number; failedJobs: number; }
export interface BrowserProfileRecord { id: string; name: string; profileDirectory: string; browserType: string; status: BrowserProfileStatus; createdAt: string; updatedAt: string; }
export interface AccountRecord { id: string; displayName: string; provider: string; browserProfileId: string | null; enabled: boolean; sessionStatus: AccountSessionStatus; lastSessionCheck: string | null; createdAt: string; updatedAt: string; }
export interface JobRecord { id: string; projectId: string; sceneNumber: number; provider: string; accountId: string | null; prompt: string; inputMedia: InputMedia; durationSeconds: number; aspectRatio: string; resolution: string; status: JobState; progress: number; priority: number; attemptCount: number; maxAttempts: number; errorCode: string | null; errorMessage: string | null; providerMetadata: Record<string, unknown> | null; createdAt: string; updatedAt: string; startedAt: string | null; submittedAt: string | null; completedAt: string | null; projectName?: string; accountName?: string | null; }
export interface JobAttemptRecord { id: string; jobId: string; attemptNumber: number; accountId: string | null; workerId: string | null; status: JobState; startedAt: string; endedAt: string | null; errorCode: string | null; errorMessage: string | null; providerMetadata: Record<string, unknown> | null; }
export interface OutputRecord { id: string; jobId: string; filePath: string; fileName: string; durationSeconds: number | null; width: number | null; height: number | null; fps: number | null; videoCodec: string | null; audioCodec: string | null; fileSize: number | null; checksumSha256: string | null; createdAt: string; }
export interface WorkerRecord { id: string; name: string; state: WorkerState; accountId: string | null; jobId: string | null; heartbeatAt: string | null; startedAt: string | null; updatedAt: string; }
export interface ApplicationLogRecord { id: string; timestamp: string; level: 'DEBUG' | 'INFO' | 'WARN' | 'ERROR'; module: string; jobId: string | null; projectId: string | null; workerId: string | null; accountId: string | null; event: string | null; message: string; metadata: Record<string, unknown> | null; }
export interface PaginatedResult<T> { items: T[]; total: number; limit: number; offset: number; }
export type ProductionRunRecord = ProductionRun;
