import React, { useCallback } from 'react';
import { Activity, CheckCircle2, CircleDashed, FolderKanban, ListOrdered, TriangleAlert } from 'lucide-react';
import { JobState } from '@ht-dola/shared';
import { jobService, logService, projectService, providerService, workerService } from '../api/services';
import { useAsyncData } from '../hooks/useAsyncData';
import { DataTable, ErrorState, LoadingState, PageHeader, ProgressBar, SectionCard, StatCard, StatusBadge, type Column } from '../components/ui';
import type { JobListItem, LogListItem, WorkerListItem } from '../types/ui';

export const DashboardPage: React.FC = () => {
  const load = useCallback(async () => { const [projects, jobs, workers, logs, providers] = await Promise.all([projectService.list(), jobService.list(), workerService.list(), logService.list(), providerService.list()]); return { projects, jobs, workers, logs, providers }; }, []);
  const { data, loading, error, reload } = useAsyncData(load);
  if (loading) return <LoadingState />; if (error || !data) return <ErrorState message={error ?? undefined} onRetry={reload} />;
  const running = data.jobs.filter((job) => [JobState.GENERATING, JobState.DOWNLOADING, JobState.PROCESSING].includes(job.state)).length;
  const waiting = data.jobs.filter((job) => [JobState.QUEUED, JobState.WAITING_FOR_WORKER].includes(job.state)).length;
  const completed = data.projects.reduce((total, project) => total + project.completedJobs, 0); const failed = data.projects.reduce((total, project) => total + project.failedJobs, 0);
  const workerColumns: Column<WorkerListItem>[] = [{ key: 'worker', header: 'Worker', cell: (row) => <strong>{row.name}</strong>, sortValue: (row) => row.name }, { key: 'account', header: 'Account', cell: (row) => row.account }, { key: 'job', header: 'Current job', cell: (row) => <span className="mono">{row.currentJob}</span> }, { key: 'state', header: 'State', cell: (row) => <StatusBadge status={row.state} /> }, { key: 'elapsed', header: 'Elapsed', cell: (row) => row.elapsed }];
  const jobColumns: Column<JobListItem>[] = [{ key: 'scene', header: 'Scene', cell: (row) => <strong className="mono accent">{row.scene}</strong>, sortValue: (row) => row.scene }, { key: 'project', header: 'Project', cell: (row) => row.project }, { key: 'provider', header: 'Provider', cell: (row) => row.provider }, { key: 'account', header: 'Account', cell: (row) => row.account }, { key: 'status', header: 'Status', cell: (row) => <StatusBadge status={row.state} /> }, { key: 'progress', header: 'Progress', cell: (row) => <ProgressBar value={row.progress} />, sortValue: (row) => row.progress }, { key: 'created', header: 'Created', cell: (row) => new Date(row.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }), sortValue: (row) => row.createdAt }, { key: 'actions', header: '', cell: () => <button className="table-action">View</button> }];
  const errors = data.logs.filter((log) => log.level === 'ERROR'); const errorColumns: Column<LogListItem>[] = [{ key: 'time', header: 'Time', cell: (row) => new Date(row.timestamp).toLocaleTimeString(), sortValue: (row) => row.timestamp }, { key: 'job', header: 'Job', cell: (row) => <span className="mono">{row.job}</span> }, { key: 'module', header: 'Module', cell: (row) => row.module }, { key: 'message', header: 'Message', cell: (row) => row.message }];
  return <div className="page-stack"><PageHeader title="Production Dashboard" description="Queue health, active workers, and recent generation activity." actions={<button className="button secondary" onClick={reload}>Refresh</button>} /><div className="stats-grid"><StatCard icon={<FolderKanban />} label="Total Projects" value={data.projects.length} meta="Local workspaces" /><StatCard icon={<ListOrdered />} label="Total Jobs" value={data.projects.reduce((sum, item) => sum + item.totalJobs, 0)} /><StatCard icon={<Activity />} label="Running" value={running} tone="default" /><StatCard icon={<CircleDashed />} label="Waiting" value={waiting} tone="warning" /><StatCard icon={<CheckCircle2 />} label="Completed" value={completed} tone="success" /><StatCard icon={<TriangleAlert />} label="Failed" value={failed} tone="danger" /></div><SectionCard title="Provider Reliability" description="Health, incidents, and circuit state">{data.providers.length===0?<p>No provider metrics recorded yet.</p>:<div className="overview-list">{data.providers.map(provider=><div key={provider.provider}><span><strong>{provider.provider}</strong> <StatusBadge status={provider.status} /> Health {provider.healthPercent}% · Circuit {provider.circuit} · Incidents {provider.incidents.filter(i=>i.status==='OPEN').length}</span><span><button className="table-action" onClick={()=>void providerService.diagnostics(provider.provider)}>Inspect Diagnostics</button>{provider.circuit==='OPEN'?<button className="table-action" onClick={()=>void providerService.resume(provider.provider).then(reload)}>Manual Resume</button>:<button className="table-action" onClick={()=>void providerService.pause(provider.provider).then(reload)}>Pause Provider</button>}</span></div>)}</div>}</SectionCard><div className="dashboard-grid"><SectionCard title="Production Overview" description="Current batch throughput"><div className="overview-list">{[['Running', running, 36], ['Waiting', waiting, 58], ['Completed', completed, 92], ['Failed', failed, 8]].map(([label, value, progress]) => <div key={label as string}><span>{label}<strong>{value}</strong></span><ProgressBar value={progress as number} label="" /></div>)}</div></SectionCard><SectionCard title="Worker Status" description="Development service abstraction"><DataTable rows={data.workers} columns={workerColumns} rowKey={(row) => row.id} pageSize={4} /></SectionCard></div><SectionCard title="Recent Jobs" description="Latest production activity"><DataTable rows={data.jobs} columns={jobColumns} rowKey={(row) => row.id} pageSize={5} /></SectionCard><SectionCard title="Recent Errors" description="Issues requiring attention"><DataTable rows={errors} columns={errorColumns} rowKey={(row) => row.id} pageSize={4} /></SectionCard></div>;
};
