import { randomUUID } from 'node:crypto';
import { JobState, type JobCreateInput, type JobListQuery, type JobUpdateInput } from '@ht-dola/shared';
import type { SqliteDatabase } from '../database.js';
import type { JobRecord, PaginatedResult } from '../types.js';
import { nowIso, parseJson } from './helpers.js';

const select=`SELECT j.id,j.project_id AS projectId,j.scene_number AS sceneNumber,j.provider,j.account_id AS accountId,j.prompt,j.input_media_json AS inputMediaJson,j.duration_seconds AS durationSeconds,j.aspect_ratio AS aspectRatio,j.resolution,j.status,j.progress,j.priority,j.attempt_count AS attemptCount,j.max_attempts AS maxAttempts,j.error_code AS errorCode,j.error_message AS errorMessage,j.provider_metadata_json AS providerMetadataJson,j.created_at AS createdAt,j.updated_at AS updatedAt,j.started_at AS startedAt,j.submitted_at AS submittedAt,j.completed_at AS completedAt,p.name AS projectName,a.display_name AS accountName FROM jobs j JOIN projects p ON p.id=j.project_id LEFT JOIN accounts a ON a.id=j.account_id`;
type JobRow=Omit<JobRecord,'inputMedia'|'providerMetadata'>&{inputMediaJson:string;providerMetadataJson:string|null};
const map=(row:JobRow):JobRecord=>{const{inputMediaJson,providerMetadataJson,...rest}=row;return{...rest,inputMedia:parseJson(inputMediaJson,{}),providerMetadata:parseJson(providerMetadataJson,null)};};

export class JobRepository {
  constructor(public readonly database:SqliteDatabase){}
  private insert(input:JobCreateInput):string {const id=randomUUID(),now=nowIso();this.database.prepare('INSERT INTO jobs (id,project_id,scene_number,provider,account_id,prompt,input_media_json,duration_seconds,aspect_ratio,resolution,status,progress,priority,attempt_count,max_attempts,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,0,?,?,?)').run(id,input.projectId,input.sceneNumber,input.provider,input.accountId??null,input.prompt,JSON.stringify(input.inputMedia),input.durationSeconds,input.aspectRatio,input.resolution,input.status,input.status===JobState.COMPLETED?100:0,input.priority,input.maxAttempts,now,now);return id;}
  create(input:JobCreateInput):JobRecord{const id=this.insert(input);return this.getById(id)!;}
  createMany(inputs:JobCreateInput[]):JobRecord[]{const ids=this.database.transaction((rows:JobCreateInput[])=>rows.map((row)=>this.insert(row)))(inputs);return ids.map((id)=>this.getById(id)!);}
  getById(id:string):JobRecord|undefined{const row=this.database.prepare(`${select} WHERE j.id=?`).get(id) as JobRow|undefined;return row?map(row):undefined;}
  list(query:JobListQuery):PaginatedResult<JobRecord>{const c:string[]=[],p:unknown[]=[];if(query.project){c.push('j.project_id=?');p.push(query.project);}if(query.status){c.push('j.status=?');p.push(query.status);}if(query.account){c.push('j.account_id=?');p.push(query.account);}if(query.provider){c.push('j.provider=?');p.push(query.provider);}if(query.aspectRatio){c.push('j.aspect_ratio=?');p.push(query.aspectRatio);}if(query.search){c.push('(j.prompt LIKE ? OR CAST(j.scene_number AS TEXT) LIKE ?)');p.push(`%${query.search}%`,`%${query.search}%`);}const w=c.length?` WHERE ${c.join(' AND ')}`:'';const total=(this.database.prepare(`SELECT COUNT(*) count FROM jobs j${w}`).get(...p)as{count:number}).count;const rows=this.database.prepare(`${select}${w} ORDER BY j.scene_number ASC LIMIT ? OFFSET ?`).all(...p,query.limit,query.offset)as JobRow[];return{items:rows.map(map),total,limit:query.limit,offset:query.offset};}
  update(id:string,input:JobUpdateInput):JobRecord|undefined{const mapping:Array<[keyof JobUpdateInput,string,(value:unknown)=>unknown]>=[['sceneNumber','scene_number',(v)=>v],['provider','provider',(v)=>v],['accountId','account_id',(v)=>v],['prompt','prompt',(v)=>v],['inputMedia','input_media_json',(v)=>JSON.stringify(v)],['durationSeconds','duration_seconds',(v)=>v],['aspectRatio','aspect_ratio',(v)=>v],['resolution','resolution',(v)=>v],['status','status',(v)=>v],['priority','priority',(v)=>v],['maxAttempts','max_attempts',(v)=>v]];const f:string[]=[],v:unknown[]=[];for(const[key,column,convert]of mapping)if(input[key]!==undefined){f.push(`${column}=?`);v.push(convert(input[key]));}if(!f.length)return this.getById(id);f.push('updated_at=?');v.push(nowIso(),id);return this.database.prepare(`UPDATE jobs SET ${f.join(',')} WHERE id=?`).run(...v).changes?this.getById(id):undefined;}
  updateStatus(id:string,status:JobState):JobRecord|undefined{return this.database.prepare('UPDATE jobs SET status=?,progress=CASE WHEN ?=? THEN 100 ELSE 0 END,updated_at=? WHERE id=?').run(status,status,JobState.COMPLETED,nowIso(),id).changes?this.getById(id):undefined;}
  nextSceneNumber(projectId:string):number{return (this.database.prepare('SELECT COALESCE(MAX(scene_number),0)+1 value FROM jobs WHERE project_id=?').get(projectId) as {value:number}).value;}
  hasOutputs(id:string):boolean{return Boolean(this.database.prepare('SELECT 1 FROM outputs WHERE job_id=? LIMIT 1').get(id));}
  delete(id:string):boolean{return this.database.prepare('DELETE FROM jobs WHERE id=?').run(id).changes>0;}
}
