import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import { monitorEventLoopDelay } from 'node:perf_hooks';
import { JobState } from '@ht-dola/shared';
import { openDatabase, type SqliteDatabase } from '../db/database.js';
import { ProjectRepository, JobRepository } from '../db/repositories/index.js';

export interface QaContext { root: string; dbPath: string; db: SqliteDatabase; projectId: string }
export interface MetricsSample { timestamp:string; rss:number; heapUsed:number; heapTotal:number; cpuUserMicros:number; cpuSystemMicros:number; activeWorkers:number; busyWorkers:number; queueDepth:number; completedJobs:number; failedJobs:number; retryCount:number; dbLatencyMs:number; eventLoopDelayMs:number; openBrowserCount:number; openChildProcessCount:number; activeDownloads:number; logBytes:number; diagnosticBytes:number }

const directoryBytes=(root:string):number=>{if(!fs.existsSync(root))return 0;let total=0;for(const entry of fs.readdirSync(root,{withFileTypes:true})){const file=path.join(root,entry.name);total+=entry.isDirectory()?directoryBytes(file):fs.statSync(file).size;}return total;};
export const createQaContext=(name:string):QaContext=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),`ht-dola-phase18-${name}-`)),dbPath=path.join(root,'qa.db'),db=openDatabase(dbPath),project=new ProjectRepository(db).create({name:`QA ${name}`,description:'Temporary Phase 18 dataset',defaultProvider:'mock'});return{root,dbPath,db,projectId:project.id};};
export const cleanupTestData=(context:QaContext)=>{if(context.db.open)context.db.close();fs.rmSync(context.root,{recursive:true,force:true});};
export const createJobs=(context:QaContext,count:number,status:JobState=JobState.QUEUED,offset=0)=>{const now=new Date().toISOString(),insert=context.db.prepare('INSERT INTO jobs (id,project_id,scene_number,provider,prompt,input_media_json,duration_seconds,aspect_ratio,resolution,status,progress,priority,attempt_count,max_attempts,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');context.db.transaction(()=>{for(let index=1;index<=count;index++){const scene=index+offset;insert.run(randomUUID(),context.projectId,scene,'mock',`Synthetic prompt ${scene}`,'{}',5,'16:9','720p',status,0,scene%7,0,3,new Date(Date.parse(now)+index).toISOString(),now);}})();};
export const completeQueuedJobs=(context:QaContext,workers:number,limit=Number.MAX_SAFE_INTEGER)=>{const select=context.db.prepare("SELECT id FROM jobs WHERE status='QUEUED' ORDER BY priority DESC,created_at ASC LIMIT 1"),claim=context.db.prepare("UPDATE jobs SET status='WAITING_FOR_WORKER',started_at=?,updated_at=? WHERE id=? AND status='QUEUED'"),attempt=context.db.prepare("INSERT INTO job_attempts (id,job_id,attempt_number,status,started_at,ended_at) VALUES (?,?,1,'COMPLETED',?,?)"),finish=context.db.prepare("UPDATE jobs SET status='COMPLETED',progress=100,attempt_count=1,completed_at=?,updated_at=? WHERE id=?"),output=context.db.prepare('INSERT INTO outputs (id,job_id,file_path,file_name,file_size,checksum_sha256,created_at) VALUES (?,?,?,?,?,?,?)');let completed=0,duplicates=0;const seen=new Set<string>(),start=performance.now();while(completed<limit){let progressed=false;for(let worker=0;worker<workers&&completed<limit;worker++){const row=select.get() as {id:string}|undefined;if(!row)break;const now=new Date().toISOString();if(!claim.run(now,now,row.id).changes)continue;if(seen.has(row.id))duplicates++;seen.add(row.id);context.db.transaction(()=>{attempt.run(randomUUID(),row.id,now,now);finish.run(now,now,row.id);output.run(randomUUID(),row.id,path.join(context.root,'outputs',`${row.id}.mp4`),`${row.id}.mp4`,48,'synthetic',now);})();completed++;progressed=true;}if(!progressed)break;}const durationMs=performance.now()-start;return{completed,duplicates,durationMs,jobsPerMinute:durationMs?completed/(durationMs/60_000):0};};
export const collectMetrics=(context:QaContext,openBrowserCount=0):MetricsSample=>{const histogram=monitorEventLoopDelay({resolution:10});histogram.enable();const before=performance.now();context.db.prepare('SELECT COUNT(*) FROM jobs').get();const dbLatencyMs=performance.now()-before;histogram.disable();const memory=process.memoryUsage(),cpu=process.cpuUsage(),counts=context.db.prepare("SELECT SUM(status='QUEUED') queueDepth,SUM(status='COMPLETED') completedJobs,SUM(status='FAILED') failedJobs,SUM(attempt_count) retryCount FROM jobs").get() as Record<string,number|null>,workers=context.db.prepare("SELECT COUNT(*) activeWorkers,SUM(state='BUSY') busyWorkers FROM workers WHERE state NOT IN ('STOPPED','OFFLINE')").get() as Record<string,number|null>;return{timestamp:new Date().toISOString(),rss:memory.rss,heapUsed:memory.heapUsed,heapTotal:memory.heapTotal,cpuUserMicros:cpu.user,cpuSystemMicros:cpu.system,activeWorkers:workers.activeWorkers??0,busyWorkers:workers.busyWorkers??0,queueDepth:counts.queueDepth??0,completedJobs:counts.completedJobs??0,failedJobs:counts.failedJobs??0,retryCount:counts.retryCount??0,dbLatencyMs,eventLoopDelayMs:Number.isFinite(histogram.mean)?histogram.mean/1e6:0,openBrowserCount,openChildProcessCount:0,activeDownloads:0,logBytes:directoryBytes(path.join(context.root,'logs')),diagnosticBytes:directoryBytes(path.join(context.root,'diagnostics'))};};
export const queryPlan=(db:SqliteDatabase,sql:string)=>db.prepare(`EXPLAIN QUERY PLAN ${sql}`).all().map(row=>JSON.stringify(row)).join('\n');
export const validateDataset=(context:QaContext,expected:number)=>{const repository=new JobRepository(context.db),total=repository.list({limit:200,offset:0}).total,unique=(context.db.prepare('SELECT COUNT(DISTINCT id) count FROM jobs').get() as {count:number}).count;return{total,unique,valid:total===expected&&unique===expected};};
