import fs from 'node:fs'; import path from 'node:path'; import { randomUUID } from 'node:crypto'; import type { ProviderErrorCode } from './ProviderErrors.js'; import { appConfig } from '../../config/app-config.js';
export type CircuitState='CLOSED'|'OPEN'|'HALF_OPEN'; export type ProviderHealthStatus='HEALTHY'|'DEGRADED'|'PAUSED'|'FORM_CHANGED'|'SESSION_ISSUE';
export interface ProviderIncident{id:string;provider:string;detectedAt:string;errorCode:ProviderErrorCode;control?:string;affectedJobs:string[];affectedAccounts:string[];screenshotCount:number;status:'OPEN'|'RESOLVED'}
interface Snapshot{provider:string;circuit:CircuitState;paused:boolean;consecutiveStructuralFailures:number;attempted:number;succeeded:number;failed:number;sessionErrors:number;formChangeErrors:number;navigationErrors:number;preparationTotalMs:number;generationTotalMs:number;incidents:ProviderIncident[];recent:Array<{success:boolean;code?:ProviderErrorCode}>}
const structural=new Set<ProviderErrorCode>(['FORM_CHANGED','CONTROL_NOT_FOUND','PAGE_NOT_RECOGNIZED','AMBIGUOUS_CONTROL']);
const fresh=(provider:string):Snapshot=>({provider,circuit:'CLOSED',paused:false,consecutiveStructuralFailures:0,attempted:0,succeeded:0,failed:0,sessionErrors:0,formChangeErrors:0,navigationErrors:0,preparationTotalMs:0,generationTotalMs:0,incidents:[],recent:[]});
export class ProviderReliabilityService{
 private states=new Map<string,Snapshot>(); constructor(private readonly file=path.join(appConfig.dataDir,'provider-reliability.json'),private readonly threshold=5){this.load();}
 private load(){try{const values=JSON.parse(fs.readFileSync(this.file,'utf8')) as Snapshot[];for(const v of values)this.states.set(v.provider,v);}catch{}}
 private save(){fs.mkdirSync(path.dirname(this.file),{recursive:true});const tmp=`${this.file}.part`;fs.writeFileSync(tmp,JSON.stringify([...this.states.values()],null,2));fs.renameSync(tmp,this.file);}
 private state(provider:string){let s=this.states.get(provider);if(!s){s=fresh(provider);this.states.set(provider,s);}return s;}
 canAssign(provider:string){const s=this.state(provider);return !s.paused&&s.circuit!=='OPEN';}
 recordSuccess(provider:string,timings:{preparationMs?:number;generationMs?:number}={}){const s=this.state(provider);s.attempted++;s.succeeded++;s.consecutiveStructuralFailures=0;s.recent.push({success:true});s.recent=s.recent.slice(-20);s.preparationTotalMs+=timings.preparationMs??0;s.generationTotalMs+=timings.generationMs??0;if(s.circuit==='HALF_OPEN')s.circuit='CLOSED';this.save();}
 recordFailure(provider:string,code:ProviderErrorCode,ctx:{jobId?:string;accountId?:string;control?:string;screenshot?:boolean}={}){const s=this.state(provider);s.attempted++;s.failed++;s.recent.push({success:false,code});s.recent=s.recent.slice(-20);if(code==='SESSION_EXPIRED'||code==='LOGIN_REQUIRED')s.sessionErrors++;if(code==='FORM_CHANGED'||code==='CONTROL_NOT_FOUND'||code==='AMBIGUOUS_CONTROL')s.formChangeErrors++;if(code==='NAVIGATION_FAILED')s.navigationErrors++;if(structural.has(code))s.consecutiveStructuralFailures++;else s.consecutiveStructuralFailures=0;let incident=s.incidents.find(i=>i.status==='OPEN'&&i.errorCode===code&&i.control===ctx.control);if(!incident){incident={id:randomUUID(),provider,detectedAt:new Date().toISOString(),errorCode:code,...(ctx.control?{control:ctx.control}:{}),affectedJobs:[],affectedAccounts:[],screenshotCount:0,status:'OPEN'};s.incidents.push(incident);}if(ctx.jobId&&!incident.affectedJobs.includes(ctx.jobId))incident.affectedJobs.push(ctx.jobId);if(ctx.accountId&&!incident.affectedAccounts.includes(ctx.accountId))incident.affectedAccounts.push(ctx.accountId);if(ctx.screenshot)incident.screenshotCount++;if(s.consecutiveStructuralFailures>=this.threshold)s.circuit='OPEN';this.save();return incident;}
 pause(provider:string){const s=this.state(provider);s.paused=true;s.circuit='OPEN';this.save();}
 resume(provider:string){const s=this.state(provider);s.paused=false;s.circuit='HALF_OPEN';this.save();}
 status(provider:string){const s=this.state(provider),successes=s.recent.filter(x=>x.success).length;const status:ProviderHealthStatus=s.paused?'PAUSED':s.circuit==='OPEN'?'FORM_CHANGED':s.sessionErrors>s.formChangeErrors&&s.sessionErrors>0?'SESSION_ISSUE':s.recent.some(x=>!x.success)?'DEGRADED':'HEALTHY';return{...s,status,healthPercent:s.recent.length?Math.round(successes/s.recent.length*100):100,averagePreparationMs:s.succeeded?Math.round(s.preparationTotalMs/s.succeeded):0,averageGenerationMs:s.succeeded?Math.round(s.generationTotalMs/s.succeeded):0};}
 all(){return[...this.states.keys()].map(p=>this.status(p));}
}
export const providerReliability=new ProviderReliabilityService();
