import { createClient, type Client } from '@libsql/client';
import { drizzle, type LibSQLDatabase } from 'drizzle-orm/libsql';
import * as schema from './schema';
const statements=[
`CREATE TABLE IF NOT EXISTS datasets(id TEXT PRIMARY KEY,name TEXT NOT NULL,source_type TEXT NOT NULL,root_path TEXT,item_count INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS dataset_items(id TEXT PRIMARY KEY,dataset_id TEXT NOT NULL REFERENCES datasets(id) ON DELETE CASCADE,file_path TEXT,source_url TEXT,platform TEXT,account_name TEXT,account_url TEXT,caption TEXT,hashtags TEXT,published_at TEXT,file_hash TEXT,duration REAL,width INTEGER,height INTEGER,fps REAL,thumbnail_path TEXT,status TEXT NOT NULL,created_at TEXT NOT NULL)`,
`CREATE UNIQUE INDEX IF NOT EXISTS idx_items_hash ON dataset_items(file_hash) WHERE file_hash IS NOT NULL`,
`CREATE TABLE IF NOT EXISTS media_features(id TEXT PRIMARY KEY,dataset_item_id TEXT NOT NULL REFERENCES dataset_items(id) ON DELETE CASCADE,perceptual_hash TEXT,audio_fingerprint TEXT,transcript TEXT,ocr_text TEXT,visual_embedding_path TEXT,text_embedding_path TEXT,scene_json TEXT,feature_version TEXT NOT NULL,created_at TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS search_jobs(id TEXT PRIMARY KEY,source_file TEXT NOT NULL,search_mode TEXT NOT NULL,dataset_ids TEXT NOT NULL,status TEXT NOT NULL,progress REAL NOT NULL,current_step TEXT NOT NULL,candidate_count INTEGER NOT NULL,deep_analysis_count INTEGER NOT NULL,error_message TEXT,created_at TEXT NOT NULL,completed_at TEXT)`,
`CREATE TABLE IF NOT EXISTS match_results(id TEXT PRIMARY KEY,search_job_id TEXT NOT NULL REFERENCES search_jobs(id) ON DELETE CASCADE,dataset_item_id TEXT NOT NULL REFERENCES dataset_items(id) ON DELETE CASCADE,match_type TEXT NOT NULL,total_score REAL NOT NULL,visual_score REAL NOT NULL,audio_score REAL NOT NULL,transcript_score REAL NOT NULL,ocr_score REAL NOT NULL,timeline_score REAL NOT NULL,evidence_json TEXT NOT NULL,confidence TEXT NOT NULL,feedback TEXT,created_at TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS processing_metrics(id TEXT PRIMARY KEY,job_id TEXT NOT NULL,bytes_read INTEGER NOT NULL,bytes_written INTEGER NOT NULL,processing_seconds REAL NOT NULL,gpu_seconds REAL NOT NULL,model_calls INTEGER NOT NULL,deep_analysis_count INTEGER NOT NULL,created_at TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS analysis_cache(id TEXT PRIMARY KEY,content_hash TEXT NOT NULL,source_path TEXT NOT NULL,pipeline_version TEXT NOT NULL,model_version TEXT NOT NULL,metadata_json TEXT,fingerprint_json TEXT,transcript_json TEXT,ocr_json TEXT,embedding_path TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`,
`CREATE UNIQUE INDEX IF NOT EXISTS idx_cache_versions ON analysis_cache(content_hash,pipeline_version,model_version)`];
export class Database { client:Client; orm:LibSQLDatabase<typeof schema>; constructor(path:string){this.client=createClient({url:`file:${path}`});this.orm=drizzle(this.client,{schema})} async init(){await this.client.execute('PRAGMA foreign_keys=ON');await this.client.execute('PRAGMA journal_mode=WAL');for(const sql of statements)await this.client.execute(sql)} async close(){this.client.close()} }
