export type SearchMode = 'EXACT_MATCH'|'NEAR_DUPLICATE'|'SEMANTIC_SIMILARITY'|'FORMAT_SIMILARITY';
export type ProcessingLevel = 'fast'|'balanced'|'deep';
export type JobStatus = 'queued'|'running'|'paused'|'completed'|'cancelled'|'failed';
export interface Dataset { id:string; name:string; sourceType:string; rootPath:string|null; itemCount:number; status:JobStatus; createdAt:string; updatedAt:string }
export interface DatasetItem { id:string; datasetId:string; filePath:string|null; sourceUrl:string|null; platform:string|null; accountName:string|null; accountUrl:string|null; caption:string|null; hashtags:string|null; publishedAt:string|null; fileHash:string|null; duration:number|null; width:number|null; height:number|null; fps:number|null; thumbnailPath:string|null; status:string; createdAt:string }
export interface MatchResult { id:string; searchJobId:string; datasetItemId:string; matchType:SearchMode; totalScore:number; visualScore:number; audioScore:number; transcriptScore:number; ocrScore:number; timelineScore:number; evidence:Record<string,unknown>; confidence:'low'|'medium'|'high'; item?:DatasetItem }
export interface SearchJob { id:string; sourceFile:string; searchMode:SearchMode; datasetIds:string[]; status:JobStatus; progress:number; currentStep:string; candidateCount:number; deepAnalysisCount:number; errorMessage:string|null; createdAt:string; completedAt:string|null }
export interface Settings { ffmpegPath:string; ffprobePath:string; pythonPath:string; whisperModel:string; ocrModel:string; datasetFolder:string; cacheFolder:string; workers:number; deepCandidateLimit:number; deleteTempFiles:boolean; computeMode:'cpu'|'gpu'|'auto'; modelCacheDirectory:string }
export interface AppStatus { datasetCount:number; videoCount:number; processingCount:number; searchCount:number; resultCount:number; storageBytes:number; processingSeconds:number; ffmpeg:'ready'|'missing'; python:'ready'|'missing'; vectorIndex:'ready'|'fallback'; connectors:{name:string;status:string}[] }
export interface SearchRequest { sourceFile:string; datasetIds:string[]; mode:SearchMode; limit:number; level:ProcessingLevel; enableWhisper:boolean; enableOcr:boolean }
export interface WorkerRequest { requestId:string; operation:'ping'|'analyze_metadata'|'extract_keyframes'|'extract_audio'|'compute_perceptual_hash'|'compute_audio_fingerprint'|'transcribe'|'transcribe_audio'|'ocr'|'run_ocr'|'embedding'|'create_image_embedding'|'create_text_embedding'|'compare_features'; inputPath:string; options:Record<string,unknown> }
export interface WorkerResponse { requestId:string; success:boolean; data:Record<string,unknown>; error:{code:string;message:string}|null }
export interface ImportSummary { datasetId:string; imported:number; duplicates:number; failed:number; errors:{path:string;message:string}[] }
export interface ProgressEvent { jobId:string; progress:number; step:string; status:JobStatus }
export interface ElectronApi { status():Promise<AppStatus>; datasets:{list():Promise<Dataset[]>;importFolder():Promise<ImportSummary|null>;importManifest():Promise<ImportSummary|null>;control(id:string,action:'pause'|'resume'|'cancel'|'reindex'|'delete'):Promise<void>}; search:{chooseSource():Promise<string|null>;start(input:SearchRequest):Promise<SearchJob>;list():Promise<SearchJob[]>;results(jobId:string):Promise<MatchResult[]>;cancel(jobId:string):Promise<void>;feedback(resultId:string,value:'relevant'|'not_relevant'):Promise<void>;export(jobId:string,format:'csv'|'xlsx'):Promise<string|null>}; settings:{get():Promise<Settings>;save(value:Settings):Promise<Settings>}; system:{openPath(path:string):Promise<void>;openUrl(url:string):Promise<void>}; onProgress(callback:(event:ProgressEvent)=>void):()=>void }
