// @ts-nocheck -- Playwright fixture objects intentionally use the smallest provider contract shape.
import assert from 'node:assert/strict'; import fs from 'node:fs'; import os from 'node:os'; import path from 'node:path'; import { after, before, describe, it } from 'node:test'; import { chromium,type Browser,type Page } from 'playwright'; import { ControlResolver } from '../providers/reliability/ControlResolver.js'; import { SafeSubmitGuard } from '../providers/reliability/SafeSubmitGuard.js'; import { ProviderStateMachine } from '../providers/reliability/ProviderStateMachine.js'; import { ProviderReliabilityService } from '../providers/reliability/ProviderReliabilityService.js'; import { generationControls } from '../providers/dola/selectors/index.js'; import { recognizeDolaPage } from '../providers/dola/PageRecognition.js'; import { MockVideoProvider } from '../providers/mock/index.js'; import type { BrowserProfile,Job,JobInput } from '@ht-dola/shared'; import { JobState } from '@ht-dola/shared';
const fixture=(name:string)=>path.join(process.cwd(),'src','tests','fixtures','provider','dola',name); let browser:Browser,page:Page;
const load=async(name:string)=>page.setContent(fs.readFileSync(fixture(name),'utf8'));
describe('Phase 17 provider reliability fixtures',()=>{before(async()=>{browser=await chromium.launch({headless:true});page=await browser.newPage();});after(async()=>browser.close());
it('recognizes normal generation with HIGH confidence and passes guard',async()=>{await load('generation-normal.html');const recognition=await recognizeDolaPage(page),generate=await new ControlResolver(page).resolve(generationControls.generate);assert.equal(recognition.state,'VIDEO_GENERATION');assert.equal(recognition.confidence,'HIGH');const guard=new SafeSubmitGuard().validate({authenticated:true,pageState:recognition.state,pageConfidence:recognition.confidence,modelConfirmed:true,promptConfirmed:true,mediaConfirmed:true,durationConfirmed:true,ratioConfirmed:true,resolutionConfirmed:true,alreadySubmitted:false,workerOwnsJob:true,attemptActive:true,generate});assert.equal(guard.safe,true);});
it('missing generate fails safely without click',async()=>{await load('generation-button-missing.html');const result=await new ControlResolver(page).resolve(generationControls.generate);assert.equal(result.state,'NOT_FOUND');const guard=new SafeSubmitGuard().validate({authenticated:true,pageState:'VIDEO_GENERATION',pageConfidence:'HIGH',modelConfirmed:true,promptConfirmed:true,mediaConfirmed:true,durationConfirmed:true,ratioConfirmed:true,resolutionConfirmed:true,alreadySubmitted:false,workerOwnsJob:true,attemptActive:true,generate:result});assert.equal(guard.safe,false);if(!guard.safe)assert.equal(guard.error.code,'SUBMIT_CONTROL_MISSING');});
it('ambiguous generate never chooses the first match',async()=>{await load('generation-multiple-buttons.html');const result=await new ControlResolver(page).resolve(generationControls.generate);assert.equal(result.state,'AMBIGUOUS');assert.equal(await page.evaluate(()=>Reflect.get(window,'__clicked')??0),0);});
it('minor rename uses scoped semantic fallback',async()=>{await load('generation-button-renamed.html');const result=await new ControlResolver(page).resolve(generationControls.generate);assert.equal(result.state,'FOUND');assert.equal(result.selectedStrategy,'role');});
it('recognizes login, result and unknown fixtures positively',async()=>{await load('login-required.html');assert.equal((await recognizeDolaPage(page)).state,'LOGIN_REQUIRED');await load('result-ready.html');assert.equal((await recognizeDolaPage(page)).state,'RESULT_READY');await load('unexpected-page.html');assert.equal((await recognizeDolaPage(page)).state,'UNKNOWN');});});
describe('provider state, circuit and mock contract',()=>{it('rejects illegal state transitions',()=>{const machine=new ProviderStateMachine();assert.throws(()=>machine.transition('SUBMITTING'),/Illegal provider transition/);});it('clusters failures, opens circuit, isolates sessions, and survives restart',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'dola-circuit-')),file=path.join(dir,'state.json'),service=new ProviderReliabilityService(file,5);service.recordFailure('dola','LOGIN_REQUIRED',{accountId:'a1'});assert.equal(service.status('dola').circuit,'CLOSED');for(let i=0;i<5;i++)service.recordFailure('dola','CONTROL_NOT_FOUND',{jobId:`job-${i}`,accountId:`a${i%2}`,control:'generate'});const status=service.status('dola');assert.equal(status.circuit,'OPEN');assert.equal(status.incidents.find(x=>x.errorCode==='CONTROL_NOT_FOUND')?.affectedJobs.length,5);assert.equal(new ProviderReliabilityService(file,5).canAssign('dola'),false);});it('prevents a 100-job failure avalanche after form change',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'dola-stress-')),service=new ProviderReliabilityService(path.join(dir,'state.json'),5);let submitted=0;for(let i=0;i<100;i++){if(!service.canAssign('dola'))continue;submitted++;if(i<10)service.recordSuccess('dola');else service.recordFailure('dola','FORM_CHANGED',{jobId:`job-${i}`,control:'generate'});}assert.equal(submitted,15);assert.equal(service.status('dola').circuit,'OPEN');});it('Mock provider fulfills the generic lifecycle',async()=>{const provider=new MockVideoProvider(),profile={id:'p',name:'p',profileDirectory:'x',browserType:'chromium',status:'AVAILABLE',createdAt:'',updatedAt:''} as BrowserProfile,job={id:'j',profileId:'p'} as Job,input={prompt:'test',referenceImages:[],extraParams:{},durationSeconds:5,aspectRatio:'16:9'} as JobInput;await provider.initialize(profile);assert.equal((await provider.validateSession(profile)).isValid,true);await provider.prepareJob(job,input);const submission=await provider.submit(job,input);assert.equal(submission.initialState,JobState.GENERATING);await provider.checkStatus(submission.externalJobId);assert.equal((await provider.checkStatus(submission.externalJobId)).state,JobState.DOWNLOADING);await provider.cleanup();});});
