import fs from 'node:fs'; import path from 'node:path'; import type { Page } from 'playwright'; import { ControlResolver } from '../reliability/ControlResolver.js'; import { ProviderError } from '../reliability/ProviderErrors.js'; import { generationControls,modelControls,uploadControls,optionControls } from './selectors/index.js'; import { resolveDolaModel } from './DolaModels.js'; import { detectDolaCapabilities,type DolaCapabilities } from './CapabilityDetection.js';
export interface PreparationResult{state:'READY_TO_SUBMIT';issues:[];controls:string[];capabilities:DolaCapabilities;verification:{model:boolean;prompt:boolean;media:boolean;duration:boolean;aspectRatio:boolean;resolution:boolean}}
const validateMedia=(file:string,extensions:readonly string[])=>{if(!fs.existsSync(file))throw new ProviderError('UPLOAD_FAILED',`Media file not found: ${file}`);if(!extensions.includes(path.extname(file).toLowerCase()))throw new ProviderError('UPLOAD_FAILED',`Unsupported media type: ${path.extname(file)}`);};
const requireControl=async(r:ControlResolver,definition:Parameters<ControlResolver['resolve']>[0],missing:'PROMPT_CONTROL_MISSING'|'UPLOAD_CONTROL_MISSING'|'CONTROL_NOT_FOUND')=>{const result=await r.resolve(definition);if(result.state==='AMBIGUOUS')throw new ProviderError('AMBIGUOUS_CONTROL',`${definition.id} is ambiguous.`,{control:definition.id,tried:result.tried});if(result.state!=='FOUND'||!result.locator)throw new ProviderError(missing,`${definition.id} is unavailable.`,{control:definition.id,state:result.state,tried:result.tried});return result.locator;};
const normalizePrompt=(value:string)=>value.replace(/\r\n/g,'\n');
export const prepareDolaForm=async(page:Page,input:{prompt:string;modelAlias?:string|undefined;image?:string|undefined;video?:string|undefined;audio?:string|undefined;duration?:number|undefined;aspectRatio?:string|undefined;resolution?:string|undefined}):Promise<PreparationResult>=>{if(!input.prompt.trim())throw new ProviderError('INVALID_PROVIDER_STATE','Prompt is required.');const r=new ControlResolver(page),capabilities=await detectDolaCapabilities(page),controls:string[]=[];const verification={model:!input.modelAlias,prompt:false,media:true,duration:input.duration===undefined,aspectRatio:input.aspectRatio===undefined,resolution:input.resolution===undefined};const prompt=await requireControl(r,generationControls.prompt,'PROMPT_CONTROL_MISSING');await prompt.fill(input.prompt);verification.prompt=normalizePrompt(await prompt.inputValue())===normalizePrompt(input.prompt);if(!verification.prompt)throw new ProviderError('INVALID_PROVIDER_STATE','Prompt read-back did not match requested text.');controls.push('prompt');
if(input.modelAlias){const model=await requireControl(r,modelControls.model,'CONTROL_NOT_FOUND');await model.click();const names=resolveDolaModel(input.modelAlias);let selected=false;for(const name of names){const result=await r.resolve({id:`model_option:${name}`,candidates:[{strategy:'role',role:'option',name,exact:true}]});if(result.state==='AMBIGUOUS')throw new ProviderError('AMBIGUOUS_CONTROL','Model option is ambiguous.',{model:name});if(result.state==='FOUND'&&result.locator){await result.locator.click();selected=true;break;}}if(!selected)throw new ProviderError('MODEL_NOT_AVAILABLE',`Requested model alias ${input.modelAlias} is unavailable.`);const displayed=(await model.textContent().catch(()=>''))??'';verification.model=names.some(name=>displayed.toLowerCase().includes(name.toLowerCase()));if(!verification.model)throw new ProviderError('INVALID_PROVIDER_STATE','Model selection could not be verified.');controls.push('model');}
for(const [kind,file,definition,extensions] of [['image',input.image,uploadControls.image,['.jpg','.jpeg','.png','.webp']],['video',input.video,uploadControls.video,['.mp4','.mov','.webm']],['audio',input.audio,uploadControls.audio,['.mp3','.wav','.m4a']]] as const){if(!file)continue;validateMedia(file,extensions);const upload=await requireControl(r,definition,'UPLOAD_CONTROL_MISSING');await upload.setInputFiles(file);const uploaded=await page.waitForFunction((name)=>document.body.textContent?.includes(String(name))??false,path.basename(file),{timeout:15_000}).then(()=>true).catch(()=>false);if(!uploaded)throw new ProviderError('UPLOAD_FAILED',`${kind} upload was not acknowledged by provider UI.`);controls.push(kind);}
for(const [name,value,definition,key] of [['duration',input.duration,optionControls.duration,'duration'],['aspectRatio',input.aspectRatio,optionControls.aspectRatio,'aspectRatio'],['resolution',input.resolution,optionControls.resolution,'resolution']] as const){if(value===undefined)continue;const control=await requireControl(r,definition,'CONTROL_NOT_FOUND');await control.selectOption(String(value));const selected=await control.inputValue().catch(()=> '');verification[key]=selected===String(value);if(!verification[key])throw new ProviderError('INVALID_PROVIDER_STATE',`${name} selection could not be verified.`);controls.push(name);}
return{state:'READY_TO_SUBMIT',issues:[],controls,capabilities,verification};};
